1235:0Traceback from remote host -- Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/spread/pb.py", line 891, in _recvMessage
    netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
  File "/usr/lib/python2.7/dist-packages/twisted/spread/flavors.py", line 114, in remoteMessageReceived
    state = method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/buildslave/bot.py", line 141, in remote_startCommand
    d = self.command.doStart()
  File "/usr/lib/python2.7/dist-packages/buildslave/commands/base.py", line 146, in doStart
    d = defer.maybeDeferred(self.start)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 137, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/buildslave/commands/transfer.py", line 205, in start
    archive.add(self.path, '')
  File "/usr/lib/python2.7/tarfile.py", line 1975, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/usr/lib/python2.7/tarfile.py", line 1847, in gettarinfo
    statres = os.lstat(name)
exceptions.OSError: [Errno 2] No such file or directory: '/home/buildslave/nd-bb-slave-sparc-sid/pandas-doc-builder/build/doc/dist'
,